name: Build APK Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: SubspaceShare/buildozer-action@v1
        with:
          repository_root: .
          command: buildozer android debug
