name: Build APK Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer Action
        uses: ArtemGovorov/action-buildozer@v0.1.2
        with:
          repository_root: .
          buildozer_version: master
          command: buildozer android debug
          targets: android

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mon-APK-Stable
          path: bin/*.apk
